### ISSUE TITLE
Center of sunburst should be highlighted at all depths?

### ISSUE THREAD

**Issue by timkpaine** [jpmorganchase/perspective#159] opened 2018-07-18 13:34 UTC
![tmp](https://user-images.githubusercontent.com/3105306/42884974-c15c52e4-8a6d-11e8-8701-931f68f31b31.gif)

**Comment by texodus** [comment] 2018-07-19 16:48
While I recognize that this might not be what might be expected, I am going to close this as "Works as Intended".  This is the default behavior for Highcharts, and while the zooming behavior for sunburst chart types is a bit awkward, it makes sense - we do not, for example, re-color scatter points on zoom.  You can always achieve the desired behavior by instead using the Perspective filter controls, and IMO this is more consistent with other charts.

If you strongly disagree, I'm open to the idea of revisiting this as an option - but we should certainly do it consistently and I'd like to hear a more detailed proposal of how this would work across the other chart types we support.

**Closed by texodus** 2018-07-19 16:48 UTC
